CREATE TABLE Patients (
    patient_id INT PRIMARY KEY IDENTITY(1,1),
    first_name NVARCHAR(50) NOT NULL,
    last_name NVARCHAR(50) NOT NULL,
    gender NVARCHAR(10),
    date_of_birth DATE,
    contact_number NVARCHAR(15),
    address NVARCHAR(200),
    registration_date DATE DEFAULT GETDATE(),
    insurance_provider NVARCHAR(100),
    insurance_number NVARCHAR(50),
    email NVARCHAR(100)
);

CREATE TABLE Doctors (
    doctor_id INT PRIMARY KEY IDENTITY(1,1),
    first_name NVARCHAR(50) NOT NULL,
    last_name NVARCHAR(50) NOT NULL,
    specialization NVARCHAR(100),
    phone_number NVARCHAR(15),
    years_experience INT,
    hospital_branch NVARCHAR(100),
    email NVARCHAR(100)
);

CREATE TABLE Appointments (
    appointment_id INT PRIMARY KEY IDENTITY(1,1),
    patient_id INT FOREIGN KEY REFERENCES Patients(patient_id),
    doctor_id INT FOREIGN KEY REFERENCES Doctors(doctor_id),
    appointment_date DATE,
    appointment_time TIME,
    reason_for_visit NVARCHAR(200),
    status NVARCHAR(20) DEFAULT 'Pending'
);

CREATE TABLE Treatments (
    treatment_id INT PRIMARY KEY IDENTITY(1,1),
    appointment_id INT FOREIGN KEY REFERENCES Appointments(appointment_id),
    treatment_type NVARCHAR(100),
    description NVARCHAR(500),
    cost DECIMAL(10,2),
    treatment_date DATE DEFAULT GETDATE()
);

CREATE TABLE Billing (
    bill_id INT PRIMARY KEY IDENTITY(1,1),
    patient_id INT FOREIGN KEY REFERENCES Patients(patient_id),
    treatment_id INT FOREIGN KEY REFERENCES Treatments(treatment_id),
    bill_date DATE DEFAULT GETDATE(),
    amount DECIMAL(10,2),
    payment_method NVARCHAR(50),
    payment_status NVARCHAR(20) DEFAULT 'Unpaid'
);
SELECT * FROM Patients;
SELECT * FROM Doctors;
SELECT * FROM Appointments;
SELECT * FROM Treatments;
SELECT * FROM Billing;

-- Count total number of registered patients
SELECT COUNT(*) AS total_patients FROM Patients;
SELECT TOP 10 patient_id ,first_name FROM Patients;

-- Count patients by gender
SELECT gender,COUNT(*) AS Total FROM Patients GROUP BY gender;

-- List doctor details with specialization
SELECT doctor_id,first_name,specialization FROM Doctors;

-- Count doctors by specialization
SELECT specialization,COUNT(*) AS total_doctors FROM doctors GROUP BY specialization;

-- Fetch appointments with patient and doctor names for a specific date
SELECT a.appointment_id, p.first_name, d.first_name, a.appointment_date
FROM Appointments a JOIN Patients p on a.patient_id = p.patient_id 
JOIN doctors d ON a.doctor_id = d.doctor_id WHERE 
a.appointment_date = '2023-12-26';

-- Index created for future scalability when appointment data grows
CREATE INDEX idx_appointments_date
ON Appointments(appointment_date);

-- Get the 10 most recent appointment date
SELECT TOP 10 Appointment_date FROM Appointments 
ORDER BY appointment_date DESC;

-- View column names and data types of Appointments table
SELECT COLUMN_NAME , DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'appointments';

-- Fetch all appointments sorted by latest date
SELECT a.appointment_id, p.first_name, d.first_name, 
a.appointment_date FROM Appointments a
JOIN Patients p on a.patient_id = p.patient_id 
JOIN doctors d ON a.doctor_id = d.doctor_id
ORDER BY a.appointment_date desc;

-- Identify repeat patients (visited more than once)
SELECT p.patient_id,COUNT(a.appointment_id) 
AS visit_count FROM patients p JOIN Appointments a 
ON p.patient_id = a.patient_id 
GROUP BY p.patient_id HAVING COUNT(a.appointment_id)>1
ORDER BY visit_count DESC;

-- Calculate total revenue generated by each department
SELECT d.specialization AS department, SUM(b.amount)
AS total_revenue FROM billing b JOIN doctors d 
ON d.doctor_id = d.doctor_id 
GROUP BY d.specialization 
ORDER BY total_revenue DESC;

-- Identify top 2 most busy doctors based on appointment count
SELECT TOP 2 d.first_name, d.specialization,
COUNT(a.appointment_id) AS total_appointments
FROM Doctors d JOIN Appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.first_name, d.specialization
ORDER BY total_appointments DESC;
